### ISSUE TITLE
(index):25 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:49339/node_modules/ng2-password-strength-bar/lib/passwordStrengthBar.module

### ISSUE THREAD

**Issue by mauroherlein** [rnadler/ng2-password-strength-bar#11]
i add the package on my system.config.js

System.config ({
path: {
    'npm:': 'node_modules/'
},
map: {
    'app': '/app'

    (...)Other packages

    'ng2-password-strength-bar': 'npm:ng2-password-strength-bar/index.js',
},
}
and this is the problem

(index):25 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:49339/node_modules/ng2-password-strength-bar/lib/passwordStrengthBar.module
	Error: XHR error (404 Not Found) loading http://localhost:49339/node_modules/ng2-password-strength-bar/lib/passwordStrengthBar.module
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:49339/node_modules/zone.js/dist/zone.js:1070:39)
	    at ZoneDelegate.invokeTask (http://localhost:49339/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:49339/node_modules/zone.js/dist/zone.js:191:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:49339/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:49339/node_modules/zone.js/dist/zone.js:1349:10)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:49339/node_modules/zone.js/dist/zone.js:1358:13)
	Error loading http://localhost:49339/node_modules/ng2-password-strength-bar/lib/passwordStrengthBar.module as "./lib/passwordStrengthBar.module" from http://localhost:49339/node_modules/ng2-password-strength-bar/index.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:49339/node_modules/zone.js/dist/zone.js:1070:39)
	    at ZoneDelegate.invokeTask (http://localhost:49339/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:49339/node_modules/zone.js/dist/zone.js:191:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:49339/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:49339/node_modules/zone.js/dist/zone.js:1349:10)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:49339/node_modules/zone.js/dist/zone.js:1358:13)
	Error loading http://localhost:49339/node_modules/ng2-password-strength-bar/lib/passwordStrengthBar.module as "./lib/passwordStrengthBar.module" from http://localhost:49339/node_modules/ng2-password-strength-bar/index.

**Comment by rnadler** [comment]
It looks like the contents of the package installation may be bad. Try re-installing:
```
$ rm -rf node_modules/ng2-password-strength-bar
$ npm install
```

**Comment by mauroherlein** [comment]
Thanks for replying, I solved my problem by removing SystemJS and adding the *.js generated by webpack on the index.cshtml. This work.
